### PR TITLE
Add a README.md

### PR DESCRIPTION
**Pull request by FluXy**
We should probably ask Lukas Meindl to test the Linux state of things? :)

### CODE REVIEW

**Comment by niello** [comment]
I think it is better to complete main features first, then other platforms can be tested. But if Lukas wants to build the port now for any other reason I definitely want to hear about his building process details:)

**Comment by Ident** [comment]
I do not use Linux

**Comment by FluXy** [comment]
Ah sorry, I think I got that mixed up with Martin Preisler :)

He doesn't seem to be active anymore though?

**Comment by Ident** [comment]
He has no time for CEGUI currently. He is aware of this github project though

**Comment by Ident** [comment]
He actually follows it ;)

**Pull request merged**
